Added new arrays exercises 11-15
marcinboby/java-exercises pull request #16
Opened 2023-02-19 22:48 UTC by marcinboby

2023-02-20 09:31 UTC, krzysztofszymanski requested changes

2023-02-20 09:31 UTC, krzysztofszymanski commented on src/arrays/exercise013/Exercise013.java
> +
Spróbuj to na Set zrobić i różnicy setów.

2023-02-20 09:31 UTC, krzysztofszymanski commented on src/arrays/exercise015/Exercise015.java
> +                    arrLength--;
Skrócenie długości podczas pętli śmierdzi błędami. Zobaczę później dokładnie, ale wydaje się ze tu nie gra.

2023-02-20 21:14 UTC, marcinboby commented on src/arrays/exercise015/Exercise015.java
> +                    arrLength--;
Zmieniłem na hashSet w [0c5f449]

2023-02-20 21:23 UTC, marcinboby commented on src/arrays/exercise013/Exercise013.java
>  import java.util.ArrayList;
Kurde, mogłem jeszcze zoptymalizować importy

2023-02-21 20:52 UTC, krzysztofszymanski approved these changes

2023-02-21 20:56 UTC, merged